# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4dcbdf0c1f020eaca71fe7a559246641f1bb1d16ab20edea701d3917bc4142550cbe24e94ae1598f0664161a47bd295a7dea50772c1634d04714d09b19f9e8bb

test:
  secret_key_base: c15be9d2d4c3a8f55d50d7c95d5b0ad2a35542443cde710be0aa7e0125a9016efc7068a0f1d25d62b2d50f9b303897e1f914c1ef5096332f87801510c5d520a7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
